welcomeCoupon:
  active: true
  title: Bem-vinda à Estilo Chic!
  description: "**5% de desconto** para sua primeira compra!"
  buttonText: Resgatar Meu Cupom
  whatsappMessage: Olá! Vim pelo site e quero meu desconto de boas-vindas!
persistentCoupon:
  active: true
  title: Oferta do Dia!
  description: Aproveite a **PROMO10** e ganhe 10% de desconto no Batom matte e
    Corretivo. Não perca!
  buttonText: Aproveitar
  code: PROMO10
